### ISSUE TITLE
Tic Tac Toe - Missing winning condition

### ISSUE THREAD

**Issue by JohnPPP** [NTT123/a0-jax#4]
Hi,

We have the winning condititons identified:

![image](https://user-images.githubusercontent.com/10357829/186950609-56725779-d742-4cb1-8f92-0bc888db1422.png)

I think we might have missed winning by 3 in a row in the middle (vertically and horizontally), i.e., with spaces 1 , 4 7 (vertical) and 3, 5 6 (horizontal)

I have no idea how to fix this in your code :( sorry!

**Comment by JohnPPP** [comment]
I want to add that I only noticed this after training and playing against it :) So it did learn based on these rules :) 

![image](https://user-images.githubusercontent.com/10357829/186952027-effc0b96-4055-4934-89b8-07a8707d8889.png)

**Comment by NTT123** [comment]
Hi @JohnPPP, thank you for reporting this. I will look into the issue when I have a bit of free time.
