### ISSUE TITLE
question on 9x9 go agent training

### ISSUE THREAD

**Issue by hyu2000** [NTT123/a0-jax#8]
the 9x9 go agent is pretty strong!  how many iterations was it trained on? how long does it take to train (i saw it's on TPUs)?

**Comment by NTT123** [comment]
Hi @hyu2000, I don't recall exactly how many iterations but it is more than 100.
It is about 1-2 weeks of training on 1 TPUv3.

**Comment by hyu2000** [comment]
Thanks.  Is it using the same parameters as in the README, i.e. 102400 games per iteration, 32 simulations per move?

**Comment by NTT123** [comment]
Yes. I think so.

**Comment by NTT123** [comment]
closed due to inactivity!
